// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_HARDWARE_CRYPTO_G_HPP_
#define PIGEON_HARDWARE_CRYPTO_G_HPP_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace hardware_crypto {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class HardwareCryptoApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class HardwareCryptoApi {
 public:
  HardwareCryptoApi(const HardwareCryptoApi&) = delete;
  HardwareCryptoApi& operator=(const HardwareCryptoApi&) = delete;
  virtual ~HardwareCryptoApi() {}
  virtual ErrorOr<bool> IsSupported() = 0;
  virtual void ImportPEMKey(
    const std::string& alias,
    const std::string& key,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void GenerateKeyPair(
    const std::string& alias,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ExportPublicKey(
    const std::string& alias,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  virtual void DeleteKeyPair(
    const std::string& alias,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void Sign(
    const std::string& alias,
    const std::vector<uint8_t>& data,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;

  // The codec used by HardwareCryptoApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `HardwareCryptoApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    HardwareCryptoApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  HardwareCryptoApi() = default;

};
}  // namespace hardware_crypto
#endif  // PIGEON_HARDWARE_CRYPTO_G_HPP_
